{{- if and .Values.createClusterRoles .Values.clusterRoleRules.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" (dict "context" . "component" .Values.name "name" .Values.name) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "serviceAccountName" . }}
  namespace: {{ include "namespace" . }}
{{- end }}
