apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  name: {{ template "fullname" . }}
  namespace: {{ include  "namespace" . }}
  labels:
    {{- include "labels" (dict "context" . "component" .Values.name "name" .Values.name) | nindent 4 }}
spec:
  {{- with include "strategy" .Values.deploymentStrategy }}
  strategy:
    {{- trim . | nindent 4 }}
  {{- end }}
  {{- if not (or .Values.autoscaling.enabled .Values.kedaAutoscaling.enabled) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 5 }}
  selector:
    matchLabels:
      {{- include "selectorLabels" (dict "context" . "name" .Values.name) | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- range $key, $value := . }}
        {{- if (contains "\n" $value) }}
        {{ print (printf "%s: |\n%s" $key (trim $value | nindent 10)) | replace "\n\n" "\n" }}
        {{- else }}
        {{ $key }}: {{ tpl $value $ | quote }}
        {{- end }}
        {{- end }}
        {{- end }}
      labels:
        {{- include "labels" (dict "context" . "component" .Values.name "name" .Values.name) | nindent 8 }}
        {{- with .Values.podLabels }}
          {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.runtimeClassName }}
      runtimeClassName: {{ . }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- end }}
      serviceAccountName: {{ include "serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      containers:
      - name: {{ template "fullname" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        command:
        {{- with .Values.command }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        args:
        {{- with .Values.args }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        env:
          {{- with .Values.env }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- with include "configs.envFrom" . }}
        envFrom:
          {{- trim . | nindent 10 }}
        {{- end }}
        volumeMounts:
        {{- if .Values.podVolumeMounts }}
          {{- tpl (toYaml .Values.podVolumeMounts) $ | nindent 8 }}
        {{- end }}
        ports:
        {{- with .Values.containerPorts }}
            {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.livenessProbe.enabled }}
        {{- with .Values.livenessProbe}}
        livenessProbe:
          {{- with .method }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
          initialDelaySeconds: {{ .initialDelaySeconds | default 10 }}
          periodSeconds: {{ .periodSeconds | default 10 }}
          timeoutSeconds: {{ .timeoutSeconds | default 1 }}
          successThreshold: {{ .successThreshold | default 1 }}
          failureThreshold: {{ .failureThreshold | default 10 }}
        {{- end }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        {{- with .Values.readinessProbe}}
        readinessProbe:
          {{- with .method }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
          initialDelaySeconds: {{ .initialDelaySeconds | default 10 }}
          periodSeconds: {{ .periodSeconds | default 10 }}
          timeoutSeconds: {{ .timeoutSeconds | default 1 }}
          successThreshold: {{ .successThreshold | default 1 }}
          failureThreshold: {{ .failureThreshold | default 10 }}
        {{- end }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- with .Values.containerSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.lifecycle }}
        lifecycle:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.extraContainers }}
        {{- tpl (toYaml .) $ | nindent 6 }}
      {{- end }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- tpl (toYaml .) $ | nindent 6 }}
      {{- end }}
      {{- with include "affinity" (dict "context" . "component" .Values) }}
      affinity:
        {{- tpl . $ | trim | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- range $constraint := . }}
      - {{ toYaml $constraint | nindent 8 | trim }}
        {{- if not $constraint.labelSelector }}
        labelSelector:
          matchLabels:
            {{- include "selectorLabels" (dict "context" $ "name" $.Values.name) | nindent 12 }}
        {{- end }}
        {{- end }}
      {{- end }}
      volumes:
      {{- with .Values.podVolumes }}
        {{- tpl (toYaml .) $ | nindent 6 }}
      {{- end }}
      {{- if .Values.hostNetwork }}
      hostNetwork: {{ .Values.hostNetwork }}
      {{- end }}
      {{- with .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      dnsPolicy: {{ .Values.dnsPolicy }}
