{{- if .Values.configs.cm.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-default
  namespace: {{ include  "namespace" . }}
  labels:
    {{- include "labels" (dict "context" . "component" .Values.name "name" .Values.name) | nindent 4 }}
  {{- with .Values.configs.cm.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
data:
  {{- range $k, $v := .Values.configs.cm.data }}
  {{- if kindIs "slice" $v }}
  {{ $k }}: {{ $v | toJson | squote }}
  {{- else if kindIs "map" $v }}
  {{ $k }}: {{ $v | toJson | squote }}
  {{- else }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- end }}
{{- end }}
