{{- range .Values.configs.extraSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    {{- include "labels" (dict "context" $ "component" $.Values.name "name" $.Values.name) | nindent 4 }}
  name: {{ template "fullname" $ }}-{{ .name }}
  namespace: {{ include  "namespace" $ }}
spec:
  secretStoreRef:
    name: {{ .secretStoreRef.name }}
    kind: ClusterSecretStore
  refreshInterval: {{ .refreshInterval }}
  target:
    name: {{ template "fullname" $ }}-{{ .name }}
    creationPolicy: Owner
    {{- with .targetTemplate }}
    template:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  data:
  {{- range .data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ tpl (toYaml .remoteRef.key) $ }}
        version: {{ .remoteRef.version | default "latest" }}
        conversionStrategy: {{ .remoteRef.conversionStrategy | default "Default" }}
        decodingStrategy: {{ .remoteRef.decodingStrategy | default "None" }}
        metadataPolicy: {{ .remoteRef.metadataPolicy | default "None" }}
  {{- end }}
{{- end }}
